### PR TITLE
Fix a bug that getRawMinX is called in measureXLabel instead of getMinX

### PR DESCRIPTION
**Pull request by k-kagurazaka**
It's a tiny mistake.

### CODE REVIEW

**Comment by hogelog** [comment]
I forget these code's behavior detail.
Is there any example?

- Before/After screenshot with sample code

or

- Testcase

**Comment by k-kagurazaka** [comment]
Example code that a problem occurs:

```java
        // Generate points.
        List<LineChartView.Point> points = new ArrayList<>();
        points.add(new LineChartView.Point(1000, 1));
        points.add(new LineChartView.Point(100000, 2));

        // Use a large font.
        LineChartStyle style = new LineChartStyle();
        style.setLabelTextSize(40);

        // LineChartView settings.
        chartView  = (LineChartView) findViewById(R.id.chart_view);
        chartView.setStyle(style);
        chartView.setManualMinX(0);
        chartView.setManualMaxX(100000);
        chartView.setManualXGridUnit(50000);
        chartView.setPoints(points);
```

Before/After screen shots:

before
after

A remarkable point is the lower right of screenshots.
In this case, current LineChartView set the right margin to the half length of "51,000" instead of "100,000", so the rightmost X label is cut off.

**Comment by hogelog** [comment]
LGTM :+1:

**Comment by hogelog** [comment]
Released as `0.1.8` https://search.maven.org/#artifactdetails%7Corg.hogel%7Cline-chart-view%7C0.1.8%7Cjar

**Pull request merged**
